# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Djh20200513-conn'
    subscriptionId: '2f106c03-9b32-42ee-be11-99d0286aba1a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Djh20200513QaGroup'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'azureresources/azuredeploy.json'
    overrideParameters: '-projectName djh20200513 -linkedTemplateUri https://raw.githubusercontent.com/dhorrigan/Djh20200513/master/azureresources/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
